### ISSUE TITLE
请问一下这个模型可以处理中文会议吗

### ISSUE THREAD

**Issue by Sperao** [xcfcode/DDAMS#1]

**Comment by xcfcode** [comment]
您好，首先需要中文的对话篇章结构解析器，按照我的了解，目前暂时没有。

**Comment by Sperao** [comment]
> 您好，首先需要中文的对话章节章结构解析器，按照我的了解，目前暂时没有。

能请问一下，你有知道会议摘要生成的相关中文模型没

**Comment by xcfcode** [comment]
普通的摘要模型均可以用于中文会议，但是专门针对中文会议设计的模型暂时没有。

**Comment by Sperao** [comment]
> 普通的摘要模型均可以用作中文会议，但是专门针对中文会议设计的模型暂时没有。

你知道有别人已经将英文的模型修改预处理部分而可以处理中文数据的模型吗

**Comment by xcfcode** [comment]
暂时没有😓
