### ISSUE TITLE
data set related doubts

### ISSUE THREAD

**Issue by lakshmi-imrsv** [xcfcode/DDAMS#3]
Hi i need some more details on how you got the test.relation data.I can see that it is from dialogue discourse parser.But I can see that the STAC data set  is in a different format than AMI. Can you please elaborate on obtaining the relation file?Do we need audio file in the .aa format also?

**Comment by xcfcode** [comment]
thanks for your attention. I will release the dialogue discourse parser for our meeting dataset in the next few days.

**Comment by lakshmi-imrsv** [comment]
Hi one of the input file is the speaker data which is encoded into the role vector.But the output summary file is written with the actual roles of the speaker.Can you please tell how this reverse mapping is done?

**Comment by xcfcode** [comment]
please refer to this https://github.com/xcfcode/DDAMS/tree/main/DialogueDiscourseParser

**Comment by lakshmi-imrsv** [comment]
Thank you for the prompt help.
