### ISSUE TITLE
Reproducing Shen et al. (UNS) baseline

### ISSUE THREAD

**Issue by seongminp** [xcfcode/DDAMS#6]
Hello. Thank you for your wonderful paper (and reproducible code)!

I was wondering how you obtained 37.86 R-1 on AMI for UNS. I've run the [original code](https://bitbucket.org/dascim/acl2018_abssumm/src/master/), as well as my own implementation for UNS, and consistently get around 30 R-1 on AMI.

Did you just run the original code to obtain the rouge scores? Or was `pyrouge` used? I'm guessing the test/training splits you used is the same as the original UNS paper (as can be seen from [this repo](https://github.com/xcfcode/meeting_summarization_dataset/tree/main/AMI_process)). 

I was wondering because I am using UNS as a baseline for my own paper, but noticed scores from my trials were much lower than scores reported as your baseline.

**Comment by xcfcode** [comment]
Sorry for the late reply! I also use the official codes to run the `UNS` baseline and I use `pyrouge` pkg to test rouge scores. I also set up the train/valid splits following `UNS`. Could it have been the rouge version?

**Comment by seongminp** [comment]
Thanks for the reply. I think it may have something to do with python2 -> 3 conversion and the rouge version as you mentioned. 

I'll close the issue.
