### ISSUE TITLE
Rouge didn't match

### ISSUE THREAD

**Issue by Sunnycheey** [xcfcode/DDAMS#7]
Thank you for your wonderful work!

  I'm reproducing the result, and found the calculated rouge by test_rouge.py on the AMI dataset doesn't match the reported result (the test result is 52.66-22.29-25.50, slightly lower than the reported results), have I missed something?

**Comment by xcfcode** [comment]
Hi, thanks for your attention.
Have you tried the released checkpoint? and Can you reproduce the same results as in the paper?

**Comment by xcfcode** [comment]
We can first debug whether it is caused by the ROUGE version.

**Comment by Sunnycheey** [comment]
Hi, I'm using the released checkpoint and getting the same summary as the provided summary in the repo. However, the calculated Rouge is slightly lower than the reported results.

I'm using the Pyrouge in this [repo](https://github.com/andersjo/pyrouge).

**Comment by xcfcode** [comment]
Alright, thanks for your efforts. I think this may be caused by different seeds and GPUs. 
Running the codes a few more times may mitigate this bias.
Thanks.
