### ISSUE TITLE
transformer as backbone

### ISSUE THREAD

**Issue by Sunnycheey** [xcfcode/DDAMS#8]
Hi, thanks for your great contribution. In the original paper, you note: "We have also tried Transformer [Vaswani et al., 2017] as our
backbone model.", can you provide the code that uses transformer as the backbone (I have found transformer.py in the Openmt project, but there is still a gap between that code and the hierarchical encoder)?

Thank you again.

**Comment by xcfcode** [comment]
Sorry for the inconvenience, I only kept the final model codes and removed useless codes from the remote server.

**Comment by Sunnycheey** [comment]
老哥能加个微信交流一下嘛😂

**Comment by xcfcode** [comment]
哈哈 中文好 xcfeng-hit
