### ISSUE TITLE
The speaker embedding

### ISSUE THREAD

**Issue by Sunnycheey** [xcfcode/DDAMS#9]
Hi, It's claimed that the speaker type is embedded as the one hot vector, while in [onmt/model_builder.py](https://github.com/xcfcode/DDAMS/blob/main/onmt/model_builder.py#L240) when speaker type is icsi, the vector seems **not strictly** one-hot (slightly different as a[:][0] == 1 except line 1 (start from 0)).

**Comment by xcfcode** [comment]
Hi, I have checked the code. This is indeed a bug that may be caused by *copy-paste* operations. Thanks for pointing out this. I think this may not do **huge** harm to the final results. I will re-run the codes.

**Comment by Sunnycheey** [comment]
I believe this won't affect the final result greatly too.
